ControleDeContatos/Models/BrandModel.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace BrandsCrud.Models
{
    public class BrandModel
    {
        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Digite o nome da marca.")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Digite a Nacionalidade da marca.")]
        public bool National { get; set; }

        [Required(ErrorMessage = "O status e requerido")]
        public bool Active { get; set; }
    }
}

ControleDeContatos/Models/ClientModel.cs
using System.ComponentModel.DataAnnotations;

namespace ControleDeContatos.Models
{
    public class ClientModel
    {
        [Key]
        public int Id { get; set; }

        [Required]
        public string ImageBase64 { get; set; }

        [Required]
        public string Name { get; set; }
        [Required]
        public string CPF { get; set; }
    }
}

/*
 *         protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"             
                CREATE PROCEDURE BuscarMarca
                	@NomeMarca VARCHAR(20)
                AS
                BEGIN
                	SET @NomeMarca = '%' + @NomeMarca + '%'

                	SELECT *
                	FROM dbo.Brands b
                	WHERE b.Name like @NomeMarca
                END
                ");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP PROCEDURE BuscarMarca");
        }
 * 
*/

ControleDeContatos/Models/ErrorViewModel.cs
using System;

namespace BrandsCrud.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ControleDeContatos/Controllers/BrandsController.cs
using BrandsCrud.Models;
using BrandsCrud.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;

namespace BrandsCrud.Controllers
{
    public class BrandsController : Controller
    {
        private readonly IBrandsRepository _BrandsRepository;

        public BrandsController(IBrandsRepository brandsRepository)
        {
            _BrandsRepository = brandsRepository;
        }

        public IActionResult Index()
        {
            List<BrandModel> brands = _BrandsRepository.FindAll();

            return View(brands);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Edit(int id)
        {
            BrandModel brand = _BrandsRepository.FindById(id);
            return View(brand);
        }

        public IActionResult DeleteConfirmation(int id)
        {
            BrandModel brand = _BrandsRepository.FindById(id);
            return View(brand);
        }

        public IActionResult Delete(int id)
        {
            try
            {
                bool apagado = _BrandsRepository.Delete(id);

                if(apagado) TempData["MensagemSucesso"] = "Marca apagada com sucesso!"; else TempData["MensagemErro"] = "Ops, não conseguimos cadastrar sua marca, tente novamante!";
                return RedirectToAction("Index");
            }
            catch (Exception erro)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos apagar sua marca, tente novamante, detalhe do erro: {erro.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Create(BrandModel brand)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    brand = _BrandsRepository.Add(brand);
                    TempData["MensagemSucesso"] = "Marca cadastrada com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(brand);
            }
            catch (Exception exception)
            { 
                TempData["MensagemErro"] = $"Ops, não conseguimos cadastrar sua marca, tente novamante, detalhe do erro: {exception.Message}";
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public IActionResult Edit(BrandModel brand)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    brand = _BrandsRepository.Update(brand);
                    TempData["MensagemSucesso"] = "Marca alterada com sucesso!";
                    return RedirectToAction("Index");
                }

                return View(brand);
            }
            catch (Exception exception)
            {
                TempData["MensagemErro"] = $"Ops, não conseguimos atualizar sua marca, tente novamante, detalhe do erro: {exception.Message}";
                return RedirectToAction("Index");
            }
        }
    }
}

ControleDeContatos/Controllers/ClientsController.cs
using ControleDeContatos.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Buffers.Text;
using System.IO;
using System.Threading.Tasks;

namespace ControleDeContatos.Controllers
{
    [Route("api/clients")]
    [ApiController]
    public class ClientsController : ControllerBase
    {
        private readonly IClientsRepository repository;

        public ClientsController(IClientsRepository repository) {
            this.repository = repository;
        }


        [HttpPost]
        public async Task<IActionResult> CreateClient()
        {

            try
            {
                // Recibir el formulario enviado
                var form = await Request.ReadFormAsync();

                // Obtener los valores del formulario
                var name = form["name"];
                var CPF = form["cpf"];
                var image = form["image"];

                // Validar y procesar los datos recibidos
                if (string.IsNullOrEmpty(name) || string.IsNullOrEmpty(image))
                {
                    return BadRequest("Name and image required");
                }
                // Guardar la imagen en una ubicación específica
                repository.SaveCLient(name, CPF, image);
            }
            catch (Exception ex) 
            {
                return BadRequest($"Error saving data, error detail: {ex.Message}");
            }



            // Realizar cualquier otra lógica de negocio necesaria

            return Ok("Formulario recibido y procesado correctamente.");
        }

        //endpoint to get all the clients
        [HttpGet]
        public async Task<IActionResult> GetClients()
        {
            try
            {
                var clients = await repository.GetClientList();
                return Ok(clients);
            }
            catch (Exception ex)
            {
                return BadRequest($"Error getting clients, error detail: {ex.Message}");
            }
        }


        //endpoint to get the image of a client
        [HttpGet("image/{id}")]
        public async Task<IActionResult> GetImage(int id)
        {
            try
            {
                var image = await repository.GetImage(id);
                var file = Convert.FromBase64String(image);
                return File(file, "image/png");
            }
            catch (Exception ex)
            {
                return BadRequest($"Error getting image, error detail: {ex.Message}");
            }
        }
    }
}

ControleDeContatos/Views/Brands/Create.cshtml
@model BrandModel
@{
    ViewData["Title"] = "Criar marca";
}

<div class="text-center">
    <h1 class="display-4">Cadastrar marca</h1>
</div>


<form asp-controller="Brands" asp-action="Create" method="post">

    <div class="form-group">
        <label for="nome" class="form-label">Digite o nome da marca</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Nome">
        @Html.ValidationMessageFor(x => x.Name)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">E uma marca nacional?</label>
        <input type="checkbox" asp-for="National" class="form-control">
        @Html.ValidationMessageFor(x => x.National)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">É uma marca ativa no cadastro?</label>
        <input type="checkbox" asp-for="Active" class="form-control">
        @Html.ValidationMessageFor(x => x.Active)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Adicionar</button>
    <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Brands" role="button">Voltar</a>

</form>

ControleDeContatos/Views/Brands/DeleteConfirmation.cshtml
@model BrandModel
@{
    ViewData["Title"] = "Confirmação apagar marca";
}

<div class="text-center">
    <h3>Realmente deseja apagar a marca (@Model.Name)?</h3>
</div>

<a class="btn btn-primary btn-block" asp-action="Index" asp-controller="Brands" role="button">Cancelar exclusão</a>
<a class="btn btn-danger btn-block" asp-action="Delete" asp-controller="Brands" asp-route-id="@Model.Id" role="button">Confirmar exclusão</a>

ControleDeContatos/Views/Brands/Edit.cshtml
@model BrandModel
@{
    ViewData["Title"] = "Editar marca";
}

<div class="text-center">
    <h1 class="display-4">Editar marca</h1>
</div>


<form asp-controller="Brands" asp-action="Edit" method="post">

    <input type="hidden" asp-for="Id"/>
    <div class="form-group">
        <label for="nome" class="form-label">Digite o nome da marca</label>
        <input type="text" asp-for="Name" class="form-control" placeholder="Nome">
        @Html.ValidationMessageFor(x => x.Name)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">E uma marca nacional?</label>
        <input type="checkbox" asp-for="National" class="form-control">
        @Html.ValidationMessageFor(x => x.National)
    </div>

    <div class="form-group">
        <label for="nome" class="form-label">É uma marca ativa no cadastro?</label>
        <input type="checkbox" asp-for="Active" class="form-control" >
        @Html.ValidationMessageFor(x => x.Active)
    </div>

    <button type="submit" class="btn btn-primary btn-block">Alterar</button>
    <a class="btn btn-secondary btn-block" asp-action="Index" asp-controller="Brands" role="button">Voltar</a>

</form>

ControleDeContatos/Views/Brands/Index.cshtml
@model List<BrandModel>
@{
    ViewData["Title"] = "modelos de veículos";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" asp-controller="Brands" asp-action="Create" role="button">Adicionar nova marca de veículo</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">modelos de veículos</h1>

    <table id="table-vehicles-brands" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Marca</th>
                <th scope="col">Nacional</th>
                <th scope="col">Status</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var brand in Model)
                {
                    <tr>
                        <th scope="row">@brand.Id</th>
                        <td>@brand.Name</td>
                        <td>@brand.National</td>
                        <td>@brand.Active</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-action="Edit" asp-controller="Brands" asp-route-id="@brand.Id" class="btn btn-primary">Editar</a>
                                <a role="button" asp-action="DeleteConfirmation" asp-controller="Brands" asp-route-id="@brand.Id" class="btn btn-danger">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhuma marca encontrada</td></tr>
            }
        </tbody>
    </table>

</div>

ControleDeContatos/Views/Contact/Index.cshtml
@model List<ContactModel>
@{
    ViewData["Title"] = "Listagem de Contatos";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" asp-controller="Contato" asp-action="Criar" role="button">Adicionar novo contato</a>
    </div>

    <br />

    @if (TempData["MensagemSucesso"] != null)
    {
        <div class="alert alert-success" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemSucesso"]
        </div>
    }

    @if (TempData["MensagemErro"] != null)
    {
        <div class="alert alert-danger" role="alert">
            <button type="button" class="btn btn-danger btn-sm close-alert" data-bs-dismiss="alert" aria-label="Close">X</button>
            @TempData["MensagemErro"]
        </div>
    }

    <br />

    <h1 class="display-4">Listagem de contatos</h1>

    <table id="table-contatos" class="display" style="width:100%">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Nome</th>
                <th scope="col">Email</th>
                <th scope="col">Celular</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (var contato in Model)
                {
                    <tr>
                        <th scope="row">@contato.Id</th>
                        <td>@contato.Name</td>
                        <td>@contato.Email</td>
                        <td>@contato.NumberPhone</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" asp-action="Editar" asp-controller="Contato" asp-route-id="@contato.Id" class="btn btn-primary">Editar</a>
                                <a role="button" asp-action="ApagarConfirmacao" asp-controller="Contato" asp-route-id="@contato.Id" class="btn btn-danger">Apagar</a>
                            </div>
                        </td>
                    </tr>
                }
            }
            else
            {
                <tr class="odd"><td valign="top" colspan="5">Nenhum contato encontrado</td></tr>
            }
        </tbody>
    </table>

</div>

ControleDeContatos/Views/Shared/Components/Menu/Default.cshtml
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
        aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
    <ul class="navbar-nav flex-grow-1">
        <li class="nav-item">
            <a class="nav-link text-dark" asp-area="" asp-controller="Brands" asp-action="Index">Inicio</a>
        </li>
    </ul>
</div>

ControleDeContatos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Crud Marcas de Veículos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/dt/dt-1.11.4/datatables.min.css" />


</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <partial name="Components/Menu/Default.cshtml">
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Crud Marcas de Veículos
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/dt-1.11.4/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>